spring:
  datasource:
    url: jdbc:mysql://localhost:3306/template?serverTimezone=CTT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.126.com
    username: seecoder@126.com
    password: VYPTMTMKUGYGVRLS
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 994
    properties.mail.display.sendmail: Javen
    properties.mail.display.sendname: Spring Boot Guide Email
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: seecoder@126.com
  servlet:
    multipart:
      max-file-size: 1000000000
      max-request-size: 100000000
